### ISSUE TITLE
Plan the fall

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/presentations#28]
Let's make the fall super awesome. We've talked about overhauling how we do the schedule. Let's get feedback and get people to talk about the topics.

All officers, advisers, and members of the presentations group should have access to modify the following page: https://github.com/jmunixusers/presentations/wiki/Tentative-Fall-Schedule

**Comment by lam2mo** [comment]
I added some straw man sequences based on our discussions this evening. These are not proposed schedules; they're just for reference. Feel free to revise or add to them.

**Comment by kylelaker** [comment]
At the less-than-official exec meeting on Monday night, it seemed like there was generally support for the in-progress schedule on the wiki page. This puts us at least a month into the fall semester.

**Comment by kylelaker** [comment]
We seem to have pretty well hammered out a schedule. Thanks everyone!
