### ISSUE TITLE
Provide contents under open source license

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/presentations#37]
Currently the materials here are not licensed. We should consider making them available under some sort of open source license.

We would need to determine an acceptable licensing scheme and also ensure that all contributors agree to their contributions being made available under that license.

A possible licensing scheme would be that documentation and presentations would be available under the [CC-BY-SA](https://creativecommons.org/licenses/by-sa/2.0/) and any non-trivial code snippets available under the [MIT license](https://opensource.org/licenses/MIT).

A list of all committers can be found with:

```bash
git log --format='%aN' db8a5d..HEAD | sort -u
```

**Comment by lam2mo** [comment]
Sounds good to me; you hereby have permission to make all of my contributions available under those two licenses.

**Comment by kylelaker** [comment]
@lam2mo Thanks! I need to remember to bring this up at an actual meeting and make sure that folks present are okay with it (and I'm pretty sure there won't be any opposition to this). We'll work on getting the rest of the approvals after that. Hopefully it should be a pretty smooth process.

**Comment by kylelaker** [comment]
Alright, lets move forward with getting approvals on this. I will add the people to the above message and mention them below.

**Comment by lam2mo** [comment]
Due to the lack of other comments, I'm assuming we didn't actually do this during Spring'19. Do we still wish to pursue it? If so, do you think we should try to move forward at all over the summer or just wait until Fall?

@kylelaker @ripleymj @Advill

**Comment by ripleymj** [comment]
Nothing depended on this, so I think it slipped. I'm ok with proceeding, but the internet is a little unclear on the mechanics of dual-licensing a repository (and not in the "choose which license you're downloading this under" sense). Most suggestions seem to be putting both license texts in the LICENSING.md file, with either a note at the top there or a note in README.md explaining which portions are under each license. As runnable code in this repository is somewhat rare, we probably should emphasize the CC license.

Somewhere I'd drafted a list of the 5-6 people I thought should approve the change, with the rest of the committers in the 1-2 line typo range. I'll try to find that when I get back to town, and we can tag them in a PR if we agree on the contents of it.

**Comment by kylelaker** [comment]
So looking at the repo, I don't think there is any code that this non-trivial. All of it just a few lines and anything that's longer doesn't really have any functionality. It's all just short examples (usually just for syntax). I don't think saying:

```
if [ -z "$my_variable" ]; then
   do-something
fi
```

is particularly meaningful as software or is copyrightable. I don't think that sample configuration would be either.

Originally I thought there was more significant code in this repo, but it really is mostly documentation, narrative, and examples. Solely licensing under CC-BY-SA is likely fine (as long as our contributors are okay with that). Since there isn't really software in this repo, I don't think MIT (or GPL or anything else) is really necessary.

We will want to add a note in the REAMDE.md that any link we have an `(External)` note next to is (potentially) made available under a separate license.

**Comment by lam2mo** [comment]
Seems fine to me. I think the longest code we have is the "grand finale" from the command-line tutorial--did one of us write that (it wasn't me...) or did we scrape it from somewhere else? If the latter we should give credit.

**Comment by showalrm** [comment]
I wrote the grand finale part of the command line tutorial. I wouldn't say that its significant enough to license it under a software license.
