### ISSUE TITLE
Consider using a GitHub pages project site

### ISSUE THREAD

**Issue by kylelaker** [jmunixusers/presentations#7]
Consider using a Project Site as described on the [GitHub pages](https://pages.github.com/) site. We should be able to set it to use the master branch and personally, I prefer the Minimal and Slate themes

This should allow people to view the presentations at jmunixusers.github.io/presentations (but I'm not 100% sure).

**Comment by ripleymj** [comment]
Considered: https://jmunixusers.github.io/presentations
