### ISSUE TITLE
Review PDF action

### ISSUE THREAD

**Issue by ripleymj** [jmunixusers/presentations#80]
There are multiple NPM deprecation warnings in the PDF build action, and its using Ubuntu 18.04 still. Someone should review it to make sure its as current as can be.

**Comment by cfrome77** [comment]
Here is what in the respective packages regarding the warnings. 

**marp-cli** : There is a pull request open with marp for the marp-cli to fix the highlight.js deprecation warnings that haven't been merged in yet (https://github.com/marp-team/marp-core/pull/219).

**markdown-pdf** (https://github.com/alanshaw/markdown-pdf): This package appears to not be actively maintained, having last updated/released a new version in 2019. It may sense to switch to a maintained package, but for now, the code isn't broken.

Nothing we can really do about the warnings given above. I can test out using ubuntu-latest for the OS and can make a PR if you want.
